Json file for de interleave function
CGK-Laboratory/calcium_imaging_analysis_pipeline pull request #4
Opened 2024-03-23 22:58 UTC by ccominotti

2024-03-24 21:49 UTC, ferchaure requested changes

2024-03-24 21:49 UTC, ferchaure commented on cgk_calcium_tools/files_io.py
> +        key to access output file, by default "output_movie_files". Relative path
"Relative path" unclear

2024-03-24 21:49 UTC, ferchaure commented on cgk_calcium_tools/filehandler.py
> +from files_io import (
missing relative import

2024-03-24 21:49 UTC, ferchaure commented on cgk_calcium_tools/filehandler.py
> +                                    "focus": focus,
following the other functions, it's better to try to use same keys as function arguments. In this case: input_movie_files, output_movie_files, in_efocus_values

2024-03-24 21:49 UTC, ferchaure commented on cgk_calcium_tools/filehandler.py
> +                        "focus": focus,
same as previous comment

2024-03-25 00:17 UTC, ccominotti commented on cgk_calcium_tools/files_io.py
> +        key to access output file, by default "output_movie_files". Relative path
ok

2024-04-02 16:37 UTC, ferchaure approved these changes
great work, thanks

2024-04-02 16:38 UTC, merged